### PR TITLE
Membership expression support added

### PR DESCRIPTION
**Pull request by ivanrusso**
Support for Membership Query added
https://docs.microsoft.com/en-us/sharepoint/dev/schema/membership-element-query

This branch based on previous pull request https://github.com/sadomovalex/camlex/pull/98

### CODE REVIEW

**Comment by ivanrusso** [comment]
This will solve https://github.com/sadomovalex/camlex/issues/24

**Comment by sadomovalex** [comment]
I've reviewed it now - looks good. Merged to master branch. Thank you again.
Will need to add the same features to CSOM version as well.

**Comment by ivanrusso** [comment]
where is the CSOM version? Is it on branch https://github.com/sadomovalex/camlex/tree/client

**Comment by sadomovalex** [comment]
Yes it is in this branch. Nowdays it is quite different from basic master branch and it is hard to merge automatically - so new functionality is added manually to client branch now.
Plus in CSOM version there are different build configurations (Debug, Debug15, Debug16, Debug19 - and release) for different versions of Sharepoint. When you select build configuration it references appropriate CSOM assembly from https://github.com/sadomovalex/camlex/tree/client/Assemblies folder.

If you have time to add it there also - would be great. Otherwise I will do it by myself bit later.

**Pull request merged**
